// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQtxxAvoLjXkKMdOcu0hm_S5EhRzSqnc',
    appId: '1:157556679294:web:9805f8bb130277f8632e2f',
    messagingSenderId: '157556679294',
    projectId: 'myapp-878dc',
    authDomain: 'myapp-878dc.firebaseapp.com',
    storageBucket: 'myapp-878dc.firebasestorage.app',
    measurementId: 'G-F7013BB5CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBQx2ckIhcWLNcDQFzGiLB_YPZ3PSVDfk',
    appId: '1:157556679294:android:8a87dc47a0ef939a632e2f',
    messagingSenderId: '157556679294',
    projectId: 'myapp-878dc',
    storageBucket: 'myapp-878dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFOD7Uj562UPQHmPnwrBIwY-W2JIzJkQ',
    appId: '1:157556679294:ios:1853d6f088ef362d632e2f',
    messagingSenderId: '157556679294',
    projectId: 'myapp-878dc',
    storageBucket: 'myapp-878dc.firebasestorage.app',
    iosBundleId: 'com.example.apiFlutter',
  );
}
